### ISSUE TITLE
After refuelling(?), car continues gettign fuel constantly

### ISSUE THREAD

**Issue by Joe11112** [JonBirdd/freedomrp-bugs#10]
RP Name: Marcus Sanders
Discord Name: joee#7504
Steam Name: Joe
Date of Issue: Sat 26th Jan
Have you tried to clear your cache? No
Issue: My car (at this time) is getting fuel added constantly while driving.

**Comment by JonBirdd** [comment]
> Issue: Refuelling vehicles is always completely free.

**Status Update:** Not a server side bug. Please attempt clearing your cache.
