### ISSUE TITLE
Please try x, y, z

### ISSUE THREAD

**Issue by Nyzmo** [JonBirdd/freedomrp-bugs#4]
RP Name: Danny Grey
Discord Name: Dylan#2031
Steam Name: Nyzmo
Date of Issue: 26 Jan 2019
Have you tried to clear your cache? Yes
Issue: When trying to call ems, cops or whatever it gives u a hint of who you can call. it says try calling ems, police or tow. however you cant call ems, must type medic. i think this should be more clear and say try medic rather than ems

**Comment by JonBirdd** [comment]
**Status Update:** __Resolved__

> 
> 
> RP Name: Danny Grey
> Discord Name: Dylan#2031
> Steam Name: Nyzmo
> Date of Issue: 26 Jan 2019
> Have you tried to clear your cache? Yes
> Issue: When trying to call ems, cops or whatever it gives u a hint of who you can call. it says try calling ems, police or tow. however you cant call ems, must type medic. i think this should be more clear and say try medic rather than ems

**Status Update:** __Resolved__
**Resolution:** 

- Changed notification to say `medic` rather than `ems`

- Added `ems` as an option to call

**Comment by JonBirdd** [comment]
> RP Name: Danny Grey
> Discord Name: Dylan#2031
> Steam Name: Nyzmo
> Date of Issue: 26 Jan 2019
> Have you tried to clear your cache? Yes
> Issue: When trying to call ems, cops or whatever it gives u a hint of who you can call. it says try calling ems, police or tow. however you cant call ems, must type medic. i think this should be more clear and say try medic rather than ems

**Status Update:** __Resolved__
**Resolution:** 
• Changed notification to say `medic` rather than `ems`
• Added `ems` as an option to call

**Comment by JonBirdd** [comment]
> Issue: When trying to call ems, cops or whatever it gives u a hint of who you can call. it says try calling ems, police or tow. however you cant call ems, must type medic. i think this should be more clear and say try medic rather than ems

**Status Update:** __Resolved__
**Resolution:** 
• Changed notification to say `medic` rather than `ems`
• Added `ems` as an option to call
