### ISSUE TITLE
Selling vehicles gives wrong form of money

### ISSUE THREAD

**Issue by Joe11112** [JonBirdd/freedomrp-bugs#5]
RP Name: Marcus Sanders
Discord Name: joee#7504
Steam Name: Joe
Date of Issue: Sat 26th Jan
Have you tried to clear your cache? No
Issue: Sold a vehicle, went to "GTA cash" not "FreedomRP cash" so I do not have cash in my top right, however I do have +4.5k gta cash I can't use now.

**Comment by JonBirdd** [comment]
**Status Update:** __Resolved__
**Changes Made:** Switched back to needing cash for car dealership payments. Selling vehicles will return cash.
**Commits:** https://github.com/JonBirdd/freedomrp-resources/commit/a7b0b5363d1f66082e49b502b7075b52e450aca8 then https://github.com/JonBirdd/freedomrp-resources/commit/019d77e43d8a631b1e2462059e0d4ef7d4e64fa2
