### ISSUE TITLE
Refuelling vehicles is completely free 

### ISSUE THREAD

**Issue by Joe11112** [JonBirdd/freedomrp-bugs#9]
RP Name: Marcus Sanders
Discord Name: joee#7504
Steam Name: Joe
Date of Issue: Sat 26th Jan
Have you tried to clear your cache? No
Issue: Refuelling vehicles is always completely free.

**Comment by JonBirdd** [comment]
> Issue: Refuelling vehicles is always completely free.

**Status Update:** Not a server side bug. Please attempt clearing your cache. (Keep in mind, it now takes bank money, not cash)
